sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  global:
    - GH_REF: github.com/orizens/echoes-player.git
language: node_js
node_js:
  - stable
install:
  - npm install karma-es6-shim
  - npm install
script:
  - npm run test:ci
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
after_script:
  - process.exit()
after_success:
  # - chmod +x ./config/deploy.sh
  # - ./config/deploy.sh
  - npm run build:prod
  - npm run copy:domain
  - npm run copy:heroku
  - npm run copy:package
deploy:
  provider: pages
  local_dir: ./dist
  skip_cleanup: true
  github_token: $GH_TOKEN
  name: deployed commit $TRAVIS_COMMIT from travis
  on:
    branch: master
cache:
  directories:
    - $HOME/.nvm
    - node_modules
